### ISSUE TITLE
add new member failed: etcdmain: error validating peerURLs

### ISSUE THREAD

**Issue by schmitch** [coreos/etcd#10002]
hello, after one of my nodes failed somehow I tried to re-add it, however I always get the following message:

```
etcdmain: error validating peerURLs {ClusterID:e7d9e721043e9bfa Members:[&{ID:a11f7c7b82c99552 RaftAttributes:{PeerURLs:[https://10.10.30.52:2380]} Attributes:{Name:"infra1" ClientURLs:[https://10.10.30.52:2379]}} &{ID:f7bd378938cf704d RaftAttributes:{PeerURLs:[https://10.10.30.53:2380]} Attributes:{Name: ClientURLs:[]}} &{ID:842133e992b120ec RaftAttributes:{PeerURLs:[https://10.10.30.51:2380]} Attributes:{Name:"infra0" ClientURLs:[https://10.10.30.51:2379]}}] RemovedMemberIDs:[]}: unmatched member while checking PeerURLs
```

My Members:
```
842133e992b120ec, started, "infra0", https://10.10.30.51:2380, https://10.10.30.51:2379
a11f7c7b82c99552, started, "infra1", https://10.10.30.52:2380, https://10.10.30.52:2379
f7bd378938cf704d, unstarted, , https://10.10.30.53:2380,
```

I actually had a 3 node cluster already but removed the .53er node with `member remove ID`.

Now it is stuck and can't start.
These are the values to start the node:
```
    - --initial-cluster-state=existing
    - --initial-cluster-token=x23JEn62eVUpZV82
    - --initial-advertise-peer-urls=https://10.10.30.53:2380
    - --initial-cluster="\"infra0\"=https://10.10.30.51:2380,\"infra1\"=https://10.10.30.52:2380,infra2=https://10.10.30.53:2380"
```

**Comment by schmitch** [comment]
After I removed the flags and used environment variables:

```
    env:
    - name: ETCD_NAME
      value: "infra2"
    - name: ETCD_INITIAL_CLUSTER
      value: "infra2=https://10.10.30.53:2380,\"infra0\"=https://10.10.30.51:2380,\"infra1\"=https://10.10.30.52:2380"
```

it started working... which is really really strange.
