### ISSUE TITLE
duplicate member IDs

### ISSUE THREAD

**Issue by JeanMertz** [coreos/etcd#2759]
I am probably starting `etcd2` wrong, but I can't seem to start a cluster of three (using Vagrant), using the following config:

```yaml
coreos:
  etcd2:
    discovery: https://discovery.etcd.io/xxxxxx?size=3
    advertise-client-urls: http://$public_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://$private_ipv4:2380
  units:
  - name: etcd2.service
    command: start
```

### curl http://127.0.0.1:2379/v2/stats/self

**core-01**

```json
{
  "name": "2375f063ee234451a416a6c06665ec3f",
  "id": "ce2a822cea30bfca",
  "state": "StateLeader",
  "startTime": "2015-04-25T21:14:26.510741803Z",
  "leaderInfo": {
    "leader": "ce2a822cea30bfca",
    "uptime": "21m45.012434903s",
    "startTime": "2015-04-25T21:14:27.811113055Z"
  },
  "recvAppendRequestCnt": 0,
  "sendAppendRequestCnt": 0
}
```

**core-02**

```json
{
  "name": "d96304c24a324ae49a248be1abda3aa3",
  "id": "ce2a822cea30bfca",
  "state": "StateLeader",
  "startTime": "2015-04-25T21:14:47.921500352Z",
  "leaderInfo": {
    "leader": "ce2a822cea30bfca",
    "uptime": "21m22.770412456s",
    "startTime": "2015-04-25T21:14:49.221938716Z"
  },
  "recvAppendRequestCnt": 0,
  "sendAppendRequestCnt": 0
}
```

**core-03**

```json
{
  "name": "a3bb0868814e49e8a003fe04fb7c8e2f",
  "id": "ce2a822cea30bfca",
  "state": "StateLeader",
  "startTime": "2015-04-25T21:15:09.55386747Z",
  "leaderInfo": {
    "leader": "ce2a822cea30bfca",
    "uptime": "20m58.419984115s",
    "startTime": "2015-04-25T21:15:10.854434574Z"
  },
  "recvAppendRequestCnt": 0,
  "sendAppendRequestCnt": 0
}
```

### curl http://127.0.0.1:2379/v2/stats/leader

**all three**

```json
{
  "leader": "ce2a822cea30bfca",
  "followers": {}
}
```
