### ISSUE TITLE
etcd start without error, but can't accept connection

### ISSUE THREAD

**Issue by silenceleaf** [coreos/etcd#2868]
etcd2 version: 2.01

I am using public discovery service

My configuration:

```YAML
coreos:
  etcd2:
    name: coreos1
    discovery: https://discovery.etcd.io/a0fc6f91ae40f46c1d3a6c1b4f4f34d8
    initial-cluster-token: etcd2-cluster-1
    initial-advertise-peer-urls: http://192.168.0.111:2380
    listen-peer-urls: http://192.168.0.111:2380
    advertise-client-urls: http://192.168.0.111:2379
    listen-client-urls: http://192.168.0.111:2379    
    data-dir: /home/core/etcd2/
    initial-cluster-state: new
```

Journal is OK
journalctl -b -u etcd2 --no-pager
```
May 25 13:21:21 coreos1 systemd[1]: Started etcd2.
May 25 13:21:21 coreos1 systemd[1]: Starting etcd2...
May 25 13:21:21 coreos1 etcd2[523]: 2015/05/25 13:21:21 etcd: listening for peers on http://192.168.0.111:2380
May 25 13:21:21 coreos1 etcd2[523]: 2015/05/25 13:21:21 etcd: listening for client requests on http://192.168.0.111:2379
May 25 13:21:21 coreos1 etcd2[523]: 2015/05/25 13:21:21 etcdserver: datadir is valid for the 2.0.1 format
May 25 13:21:22 coreos1 etcd2[523]: 2015/05/25 13:21:22 discovery: found self c5a74c1a94a0abf7 in the cluster
May 25 13:21:22 coreos1 etcd2[523]: 2015/05/25 13:21:22 discovery: found 1 peer(s), waiting for 4 more
```

When I use:
```
etcdctl -C 192.168.0.111:2379 member list
```
It give me
```
context deadline exceeded
```
When I check netstat -l
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        1      0 192.168.0.111:2379      *:*                     LISTEN
tcp        0      0 192.168.0.111:2380      *:*                     LISTEN

```

Recv-Q have one waiting request. I think it means network is ok. The data haven't been consumed by etcd2.

Because I can't use etcdctl, I don't know if etcd work well.

Would you mind diagnose this for me?

**Comment by xiang90** [comment]
@silenceleaf As you saw in the log, etcd is not started yet. It is still waiting for other. You have to start the other 4 peers.

**Comment by silenceleaf** [comment]
Question is even if I start other 4 peers, nothing happened in #1 machine. I can only config static mode of etcd.

**Comment by silenceleaf** [comment]
Network is fine. I can ping other machine without any issue.

**Comment by xiang90** [comment]
@silenceleaf You need to give all 5 members the same discovery token. It would be helpful if you can provide the configuration and log from all your 5 members.

**Comment by silenceleaf** [comment]
Two of my cloud config. These two machine can not find each other.

coreos1
```YAML
#cloud-config

hostname: coreos1

coreos:
  etcd2:
    name: coreos1
    discovery: https://discovery.etcd.io/a0fc6f91ae40f46c1d3a6c1b4f4f34d8
    initial-cluster-token: etcd2-cluster-1
    initial-advertise-peer-urls: http://192.168.0.111:2380
    listen-peer-urls: http://192.168.0.111:2380
    # initial-cluster: coreos1=http://192.168.0.111:2380,coreos2=http://192.168.0.112:2380,coreos3=http://192.168.0.113:2380,coreos4=http://192.168.0.114:2380,coreos5=http://192.168.0.115:2380
    advertise-client-urls: http://192.168.0.111:2379
    listen-client-urls: http://192.168.0.111:2379    
    data-dir: /home/core/etcd2/
    initial-cluster-state: new
  # fleet:
    # public-ip: 192.168.0.111
    # etcd_servers: http://192.168.0.111:2379
    # metadata: HomeCluster
  units:
    - name: 10-ens3.network
      content: |
        [Match]
        MACAddress=52:54:00:fe:b3:c1
        [Network]
        Address=192.168.0.111/24
        Gateway=192.168.0.1
        DNS=8.8.8.8
    - name: etcd2.service
      command: start
    # - name: fleet.service
    #  command: start
```

coreos2
```YAML
#cloud-config

hostname: coreos2

coreos:
  etcd2:
    name: coreos2
    discovery: https://discovery.etcd.io/a0fc6f91ae40f46c1d3a6c1b4f4f34d8
    initial-cluster-token: etcd2-cluster-1
    initial-advertise-peer-urls: http://192.168.0.112:2380
    listen-peer-urls: http://192.168.0.112:2380
    # initial-cluster: coreos1=http://192.168.0.111:2380,coreos2=http://192.168.0.112:2380,coreos3=http://192.168.0.113:2380,coreos4=http://192.168.0.114:2380,coreos5=http://192.168.0.115:2380
    advertise-client-urls: http://192.168.0.112:2379
    listen-client-urls: http://192.168.0.112:2379    
    data-dir: /home/core/etcd2/
    initial-cluster-state: new
  fleet:
    public-ip: 192.168.0.112
  units:
    - name: 10-ens3.network
      content: |
        [Match]
        MACAddress=52:54:00:fe:b3:c2
        [Network]
        Address=192.168.0.112/24
        Gateway=192.168.0.1
        DNS=8.8.8.8
    - name: etcd2.service
      command: start
    # - name: fleet.service
    #   command: start
```
