### ISSUE TITLE
etcd.service started after reboot, stopping etcd2.service all times

### ISSUE THREAD

**Issue by Nosmoht** [coreos/etcd#2908]
Hi All,

i'm fighting with is a strange issue between etcd and etcd2. I have a 6 node 
cluster running CoreOS 681.0.0 and Etcd2. Cluster works fine for several days.
Now i had to reboot all nodes. After the reboot i saw etcd.service was started.
I used 'systemctl stop etcd.service; systemctl start etcd2.service' to fix the issue.
After 10sec etcd2.service was stopped and etcd.service started again.

I guess this is due to the Restart=Always, RestartSec=10s in etcd.service. As 
i can't remove the etcd.service due to /usr is ro, i don't know how to finally 
delete etcd.service.

So two questions from my side:
1. Why did etcd.service got activated after the reboot?
2. How can make sure there is no etcd.service anymore on my system?

```yaml
#cloud-config

coreos:
  etcd2:
    discovery: <token>
    advertise-client-urls: http://<ip>:2379
    initial-advertise-peer-urls: http://<ip>:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://<ip>:2380,http://<ip>:7001
  units:
  - name: etcd2.service
    command: start
    enable: yes 
...
```
