### ISSUE TITLE
BareMetal - discovery url

### ISSUE THREAD

**Issue by tdeheurles** [coreos/etcd#3252]
I have problem with a `baremetal CoreOS` to connect to `discovery url`.

here is my etcd2 configuration :
```
etcd2:
    name: tdeheurles-bm-coreos
    listen-peer-urls: http://192.168.1.6:2380
    listen-client-urls: http://0.0.0.0:2379
    initial-advertise-peer-urls: http://192.168.1.6:2380
    advertise-client-urls: http://192.168.1.6:2379
    discovery: https://discovery.etcd.io/b9371c90aa85773de23c3c3eb52a60b9
```

What I don't understand is that this configuration work with a vagrant VM.  
I can see the VM registred at the discovery url.

PS: this discovery url is out of date
