### ISSUE TITLE
Cluster destabilises, one node using 100% CPU, others OK

### ISSUE THREAD

**Issue by fasaxc** [coreos/etcd#3261]
I'm doing a scale test with 5 etcd nodes and 1000 clients, each with their own proxy, all doing a watch.  I regularly see one node go bad and start using all available CPU.  In the logs I've checked the bad node is not the master node.  I'm running on GCE with a 16-core instance and the bad node uses all 100% of all 16 cores.  Normal nodes use approximately 15% CPU.

On the bad node, I see repeated errors in the log; on the master, I see errors trying to connect to the bad node.

Log from master node: https://gist.github.com/fasaxc/1588746681de49958556
Log from bad node: https://gist.github.com/fasaxc/8db7fcd68c8a81bb4f8d

On one run, I killed and restarted the bad etcd process and it seemed to come back and work OK.

**Comment by xiang90** [comment]
Any way we can reproduce it? We have GCE env.

**Comment by fasaxc** [comment]
Here's my scenario:

* Using CoreOS GCE image coreos-alpha-758-1-0-v20150730.  (We disable update reboots to avoid reboots in the middle of our scale test.)
* Spin up an etcd cluster using cloud config with discovery URLs.  I've seen this with a 5-VM cluster and a 9-VM cluster.  Etcd cluster is using 16-core instances with GOMAXPROCS set to 16.
* Over about 40 minutes, spin up 1000 client VMs. Each client VM has an etcd proxy running on it (we configure these by giving them the same discovery URL, after making sure that the central cluster really has com up).
* Each client VM runs an agent, which does a recursive watch on our key.  If no event occurs, it times out its socket after 90s and reconnects.  This is using python-etcd.
* Each agent also writes a few keys into etcd at startup to register itself.
* Once all the client VMs are up, we start writing to etcd in parallel from all the client VMs.  In aggregate, we're doing up to 100 writes/s under our recursively watched key.  Writes are randomly jittered.  All writes go via the local proxy.

I believe I've seen maybe one instance of this issue with a 500-client test but it seems to happen every time when I run a 1000-client test.

The etcd version is as follows:
```
$ etcd2 --version
etcd Version: 2.1.1
Git SHA: 6335fdc
Go Version: go1.4.2
Go OS/Arch: linux/amd64
```
Are there any other diagnostics I could collect from a bad instance?

**Comment by fasaxc** [comment]
Here's the cloud config from my etcd cluster:
```
#cloud-config
write_files:
  - path: /run/systemd/system/etcd2.service.d/21-gomaxproc.conf
    permissions: 0644
    owner: root
    content: |
      [Service]
      Environment="GOMAXPROCS=16"
coreos:
  update:
    reboot-strategy: off
  etcd2:
    name: $private_ipv4
    discovery: https://discovery.etcd.io/bb4b80e2eb10961f74e093f0bbfb5494
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001,http://127.0.0.1:2379,http://127.0.0.1:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
  units:
    - name: etcd2.service
      command: start
```
