### ISSUE TITLE
Add member - added member reconfiguration fail

### ISSUE THREAD

**Issue by tdeheurles** [coreos/etcd#3267]
hi, I'm trying to add a node to a cluster (*failed to find answer for the reconfiguration part of the issue*).

nodes :
- `vm0-coreos` : etcd ok - member with discovery url
- `bm0-coreos` : etcd ok - proxy with discovery url

Here is my procedure :

```bash
vm0-coreos $ etcdctl member add bm0-coreos http://192.168.1.13:2380
Added member named bm0-coreos with ID 160379697affa241 to cluster

ETCD_NAME="bm0-coreos"
ETCD_INITIAL_CLUSTER="bm0-coreos=http://192.168.1.13:2380,vm0-coreos=http://192.168.1.41:2380"
ETCD_INITIAL_CLUSTER_STATE="existing"

vm0-coreos $ etcdctl member list
160379697affa241[unstarted]: peerURLs=http://192.168.1.13:2380
300344a3f6f544e5: name=vm0-core peerURLs=http://192.168.1.41:2380 clientURLs=http://192.168.1.41:2379
```

The `bm0-coreos` initial configuration (successfully joins cluster as a proxy) :
```yaml
coreos:
  etcd2:
    name: bm0-coreos
    listen-peer-urls: http://192.168.1.13:2380
    listen-client-urls: http://192.168.1.13:2379, http://127.0.0.1:2379
    initial-advertise-peer-urls: http://192.168.1.13:2380
    advertise-client-urls: http://192.168.1.13:2379
    discovery: https://discovery.etcd.io/5eca8c4a45eaeafa560f9ff9de231f41
```
Then, I try to reconfigure `bm0-coreos` :
```yaml
coreos:
  etcd2:
    name: bm0-coreos
    listen-peer-urls: http://192.168.1.13:2380
    listen-client-urls: http://192.168.1.13:2379, http://127.0.0.1:2379
    initial-advertise-peer-urls: http://192.168.1.13:2380
    advertise-client-urls: http://192.168.1.13:2379
    discovery: https://discovery.etcd.io/5eca8c4a45eaeafa560f9ff9de231f41

    # added lines
    initial-cluster: 'bm0-coreos=http://192.168.1.13:2380,vm0-coreos=http://192.168.1.41:2380'
    initial-cluster-state: 'existing'
```

And I restart it :
```bash
bm0-coreos $ sudo systemctl stop etcd2
bm0-coreos $ sudo rm -rf /var/lib/etcd2/*
```

But `bm0-coreos` fail to join the cluster :
```
Aug 11 08:26:36 bm0-coreos systemd[1]: Started etcd2.
Aug 11 08:26:36 bm0-coreos systemd[1]: Starting etcd2...
Aug 11 08:26:36 bm0-coreos systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 08:26:36 bm0-coreos systemd[1]: etcd2.service: Unit entered failed state.
Aug 11 08:26:36 bm0-coreos systemd[1]: etcd2.service: Failed with result 'exit-code'.
Aug 11 08:26:47 bm0-coreos systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
```

Can I find more details logs ?
What should be the good reconfiguration ?

**Comment by tdeheurles** [comment]
There was finally one line of log that appear :
```
Aug 12 13:15:57 bm0-coreos etcd2[8585]: 2015/08/12 13:15:57 etcdmain: error verifying flags, multiple discovery or bootstrap flags are set. Choose one of "initial-cluster", "discovery" or "discovery-srv". See 'etcd --help'.
```

So I change the cloud-config to that (removing the discovery url too) :
```
coreos:
  etcd2:
    name: bm0-coreos
    initial-cluster: 'bm0-coreos=http://192.168.1.13:2380,vm0-coreos=http://192.168.1.41:2380'
    initial-cluster-state: 'existing'
```

And everything goes fine.
