### ISSUE TITLE
etcdserver: request timed out with requests from fleet 

### ISSUE THREAD

**Issue by bobelev** [coreos/etcd#3333]
fleet sometimes get timeouts for its requets. It happens at random time for a short time and causes fleet to reschedule all services.

Logs from etcd and fleet are here —https://gist.github.com/bobelev/832197585721f6b968b9.

cloud config
```
coreos:
  etcd2:
    discovery: https://discovery.etcd.io/
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://$private_ipv4:2379,http://127.0.0.1:2379
    listen-peer-urls: http://$private_ipv4:2380
  fleet:
    public-ip: $private_ipv4
    etcd_servers: "http://127.0.0.1:2379"
    etcd_request_timeout: 3
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
```
