### ISSUE TITLE
Use DNS name when setting initial-advertise-peer-urls

### ISSUE THREAD

**Issue by jmreicha** [coreos/etcd#3358]
I haven't been able to find any examples where DNS names are used when setting this flag, so I tried doing this myself but it looks like this flag only accepts IP addresses.  Would it be possible to extend this to accept DNS names?

**Comment by xiang90** [comment]
I think it is fine. Why do you think it is not?

**Comment by jmreicha** [comment]
@xiang90 Using this config I can get etcd2 to start up:

```
coreos:
  etcd2:
    advertise-client-urls: https://$public_ipv4:2379
    initial-advertise-peer-urls: https://$private_ipv4:2380
    listen-client-urls: https://0.0.0.0:2379
    listen-peer-urls: https://$private_ipv4:2380
    discovery: https://discovery.etcd.io/XXX
```

I have tried the following, which does NOT work.

```
coreos:
  etcd2:
    advertise-client-urls: https://$public_ipv4:2379
    initial-advertise-peer-urls: https://etcd1.example.com:2380
    listen-client-urls: https://0.0.0.0:2379
    listen-peer-urls: https://etcd1.example.com:2380
    discovery: https://discovery.etcd.io/XXX
```

I am using this drop-in unit file for additional configuration.

```
[Service]
# General settings
Environment=ETCD_DEBUG=true
# Encryption/auth
Environment=ETCD_CLIENT_CERT_AUTH=1
Environment=ETCD_TRUSTED_CA_FILE=/etc/ssl/certs/ca.crt
Environment=ETCD_PEER_KEY_FILE=/etc/ssl/etcd1.example.com.key
Environment=ETCD_PEER_CERT_FILE=/etc/ssl/certs/etcd1.example.com.crt
Environment=ETCD_CERT_FILE=/etc/ssl/certs/etcd1.example.com.crt
Environment=ETCD_KEY_FILE=/etc/ssl/etcd1.example.com.key
```

This config is for a 3 node cluster, etcd1, etcd2 and etcd3, which all have similar configs.  Maybe I am just misconfiguring something?
