### ISSUE TITLE
How to manage cluster node replacements after initial setup?

### ISSUE THREAD

**Issue by tadas-subonis** [coreos/etcd#3441]
Hi,

Sorry, if the issue/question is not at the right place, but etcd repo looks like a best choice.

I have been reading docs but it isn't entirely clear how cluster copes with etcd failures and how do I manage that.

So at the moment I have a 5 node cluster that was created using https://discovery.etcd.io discovery . So that means that now at the moment there are 3 members and 2 proxies. That is not ideal IMO and I would like to make all 5 of them members.

How do I do that?

I've tried adding one of the proxy node IPs to member list using "etcd member add ..." and later going to the nodes /var/lib/etcd2 directory, removing all content there and restarting the node. After the restart, the node still becomes a proxy node. This has probably something to do with https://discovery.etcd.io as it has set cluster size to 3. How should I update my cloud-config.yml to cope with that?

My current cloud config:
```
coreos:
  etcd2:
    discovery: https://discovery.etcd.io/xxxxxx
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
  fleet:
    public-ip: $private_ipv4
    metadata: WorkerNode=true
  units:
    - name: systemd-networkd.service
      command: start
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
```

And the next question is, how do I replace node without worrying about cluster failure? Because, at the moment, it seems I cannot kill a member node easily and add a new one. So, now let's assume that one node faileid and it is a member node and I cannot SSH into it (this has happened before). How do I add a new etcd member to the cluster and remove the old one?

Thanks

**Comment by xiang90** [comment]
> So at the moment I have a 5 node cluster that was created using https://discovery.etcd.io discovery . So that means that now at the moment there are 3 members and 2 proxies. That is not ideal IMO and I would like to make all 5 of them members.
How do I do that?

Please read https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#public-etcd-discovery-service and change size para based on your requirement (`size=5`).

> How do I add a new etcd member to the cluster and remove the old one?

https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#replace-a-failed-machine Here is the answer you were looking for.

To understand reconfiguration more, please read https://github.com/coreos/etcd/blob/master/Documentation/runtime-reconf-design.md.

**Comment by tadas-subonis** [comment]
>change size para based on your requirement (size=5).
I am aware of that, but now cluster is created and I want to change that. And I don't want to recreate cluster every time I decide to change the number of members.

After reading the second link, it seems that for the new node in its config, I should specify initial-cluster and cluster state like this, while disabling discovery, right?
```
  etcd2:
    #discovery: https://discovery.etcd.io/6f8c446ad99df1655e2c97eeeddc6c8d
    initial-cluster: infra0=http://10.0.1.10:2380,infra1=http://10.0.1.11:2380,infra2=http://10.0.1.12:2380,infra3=http://10.0.1.13:2380
    initial-cluster-state: existing
```

As per third link
>Do Not Use Public Discovery Service For Runtime Reconfiguration

It would be nice to have examples of cloud-config without using discovery.etcd.io in main docs ( https://coreos.com/os/docs/latest/cloud-config.html ).


Thanks for the links :). They are going to be helpful.

**Comment by xiang90** [comment]
> After reading the second link, it seems that for the new node in its config, I should specify initial-cluster and cluster state like this, while disabling discovery, right?

Right.

> It would be nice to have examples of cloud-config without using discovery.etcd.io in main docs

Can you submit a feature request to coreos/doc repo? Thanks a lot!

**Comment by tadas-subonis** [comment]
Do I need to specify all etcd member nodes in initial-cluster when creating a new node or is it enough to have something like this?:
```
  etcd2:
    #discovery: https://discovery.etcd.io/6f8c446ad99df1655e2c97eeeddc6c8d
    initial-cluster: some-old-node=http://10.0.1.10:2380,current_ndoe=http://10.0.1.11:2380
    initial-cluster-state: existing
```
