### ISSUE TITLE
Allow etcdctl to work with a local etcd proxy - client: etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by urzds** [coreos/etcd#4221]
I have setup a local etcd2 proxy:
```yaml
  etcd2:
    name: $<hostname>
    key-file: /srv/etcd/peer.key
    cert-file: /srv/etcd/peer.crt
    peer-key-file: /srv/etcd/peer.key
    peer-cert-file: /srv/etcd/peer.crt
    peer-client-cert-auth: true
    peer-trusted-ca-file: /etc/ssl/etcd/ca.crt
    initial-cluster: $<etcd.members>
    proxy: on
    listen-client-urls: http://localhost:2379
```

When I try to run `etcdctl`, I would assume that it works solely with the local proxy, who then communicates with the cluster members/peers. However, it appears that `etcdctl` instead just uses the proxy to lookup the cluster members/peers and then tries to talk to them directly, which will fail if the members/peers use a custom CA:
```
# etcdctl --endpoint=http://localhost:2379 --debug user list
start to sync cluster using endpoints(http://localhost:2379)
cURL Command: curl -X GET http://localhost:2379/v2/members
got endpoints(https://192.168.10.26:2379,https://192.168.10.25:2379,https://192.168.10.24:2379) after sync
Cluster-Endpoints: https://192.168.10.26:2379, https://192.168.10.25:2379, https://192.168.10.24:2379
Cluster-Endpoints: https://192.168.10.26:2379, https://192.168.10.25:2379, https://192.168.10.24:2379
cURL Command: curl -X GET https://192.168.10.26:2379/v2/auth/users
cURL Command: curl -X GET https://192.168.10.25:2379/v2/auth/users
cURL Command: curl -X GET https://192.168.10.24:2379/v2/auth/users
client: etcd cluster is unavailable or misconfigured
```

It would be nice if `etcdctl` would instead just talk to the local proxy and let that do its work.
