### ISSUE TITLE
gRPC don't work with SSL/TLS

### ISSUE THREAD

**Issue by Felixoid** [coreos/etcd#6951]
# Version
```etcd --version
etcd Version: 3.0.15
Git SHA: GitNotFound
Go Version: go1.7.3
Go OS/Arch: linux/amd64
```
# First part: noising logs from v3rpc/grpc
Config:
```
name: host01
data-dir: /var/lib/etcd/test-ssl-auto
listen-peer-urls: https://host01.domain.yandex.net:2480
listen-client-urls: https://host01.domain.yandex.net:2479,https://localhost:2479
initial-advertise-peer-urls: https://host01.domain.yandex.net:2480
initial-cluster: host01=https://host01.domain.yandex.net:2480,host02=https://host02.domain.yandex.net:2480,host03=https://host03.domain.yandex.net:2480
initial-cluster-state: new
initial-cluster-token: test-ssl
advertise-client-urls: https://host01.domain.yandex.net:2479
client-transport-security:
  auto-tls: true
peer-transport-security:
  auto-tls: true
client-cert-auth: false
```
[http2Client.notify.txt](https://github.com/coreos/etcd/files/633969/http2Client.notify.txt)
After another server connect with enabled ssl begin to repeat string:
`2016-12-06 16:31:43.093112 I | v3rpc/grpc: transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.`
I think it's the root of the next problem

# Second part: etcdctl didn't work with enabled encryption
ok, drop database, try again with `| grep -v`
Config:
```
name: host01
data-dir: /var/lib/etcd/test-ssl-auto
listen-peer-urls: https://host01.domain.yandex.net:2480
listen-client-urls: https://host01.domain.yandex.net:2479,https://localhost:2479
initial-advertise-peer-urls: https://host01.domain.yandex.net:2480
initial-cluster: host01=https://host01.domain.yandex.net:2480,host02=https://host02.domain.yandex.net:2480,host03=https://host03.domain.yandex.net:2480
initial-cluster-state: new
initial-cluster-token: test-ssl
advertise-client-urls: https://host01.domain.yandex.net:2479
client-transport-security:
  auto-tls: true
peer-transport-security:
  auto-tls: true
client-cert-auth: false
```
[auto-tls.txt](https://github.com/coreos/etcd/files/634117/auto-tls.txt)
[auto-tls-etcdctl.txt](https://github.com/coreos/etcd/files/634118/auto-tls-etcdctl.txt)

Reproduced also with valid cert+key+cacert
Config:
```name: host01
data-dir: /var/lib/etcd/test-ssl
listen-peer-urls: https://host01.domain.yandex.net:2480
listen-client-urls: https://host01.domain.yandex.net:2479,https://localhost:2479
initial-advertise-peer-urls: https://host01.domain.yandex.net:2480
initial-cluster: host01=https://host01.domain.yandex.net:2480,host02=https://host02.domain.yandex.net:2480,host03=https://host03.domain.yandex.net:2480
initial-cluster-state: new
initial-cluster-token: test-ssl
advertise-client-urls: https://host01.domain.yandex.net:2479
client-transport-security:
  cert-file: /tmp/test-ssl/certs/etcd.pem
  key-file: /tmp/test-ssl/certs/etcd.key
peer-transport-security:
  cert-file: /tmp/test-ssl/certs/etcd.pem
  key-file: /tmp/test-ssl/certs/etcd.key
  trusted-ca-file: /tmp/test-ssl/certs/caroot.crt
client-cert-auth: false
```
[tls.txt](https://github.com/coreos/etcd/files/634145/tls.txt)
[tls-etcdctl.txt](https://github.com/coreos/etcd/files/634146/tls-etcdctl.txt)

Trace of the server with the last config
[trace.txt](https://github.com/coreos/etcd/files/634508/trace.txt)
