### ISSUE TITLE
Unexpected benchmark result

### ISSUE THREAD

**Issue by cw9** [coreos/etcd#6954]
I'm running some performance test agains a 3 node etcd cluster with the following version
```
etcd --version
etcd Version: 3.0.12
Git SHA: 2d1e2e8
Go Version: go1.6.3
Go OS/Arch: linux/amd64
```

The Put benchmark looks reasonable but I'm getting some weird result from range benchmarks that the throughput of serializable reads is smaller than throughput of linearizable reads
e.g:
```
./main --conns=100 --clients=1000 --endpoints=ip1,ip2,ip3 range "key1" --total=100000 --consistency=l
bench with linearizable range
Summary:
  Total:	1.3565 secs.
  Slowest:	0.0929 secs.
  Fastest:	0.0009 secs.
  Average:	0.0132 secs.
  Stddev:	0.0140 secs.
  Requests/sec:	73716.7697

 ./main --conns=100 --clients=1000 --endpoints=ip1,ip2,ip3 range "key1" --total=100000 --consistency=s
bench with serializable range
Summary:
  Total:	1.6822 secs.
  Slowest:	0.2442 secs.
  Fastest:	0.0002 secs.
  Average:	0.0166 secs.
  Stddev:	0.0213 secs.
  Requests/sec:	59445.1270
```

If I use only one endpoint rather than all three boxes, I got this result:
```
./main --conns=100 --clients=1000 --endpoints=ip1 range "key1" --total=100000 --consistency=s
bench with serializable range
Summary:
  Total:	4.9861 secs.
  Slowest:	0.7711 secs.
  Fastest:	0.0002 secs.
  Average:	0.0494 secs.
  Stddev:	0.0678 secs.
  Requests/sec:	20055.8663

 ./main --conns=100 --clients=1000 --endpoints=ip1 range "key1" --total=100000 --consistency=l
bench with linearizable range
Summary:
  Total:	1.5002 secs.
  Slowest:	0.0386 secs.
  Fastest:	0.0018 secs.
  Average:	0.0146 secs.
  Stddev:	0.0048 secs.
  Requests/sec:	66659.7614
```

I'm trying to understand the result here because I'm expecting the linearizable reads to be slower than serializable ones, did I miss anything in the benchmark commands?

Thanks

**Comment by xiang90** [comment]
What is your machine spec? What is the config you started etcd?

Also can you try 1 client/ 1 conn case to see if s read is faster than l read?

L read does not necessarily affect throughput, it affects latency due to additional disk write. When your cluster is under heavy load, CPU might dominate. Also we have noticed some strange things around go runtime scheduling understand heavy load.

**Comment by gyuho** [comment]
Yeah seriazable read is slow due to Go runtime, we believe.

https://github.com/coreos/etcd/issues/6876

**Comment by xiang90** [comment]
@cw9 

Also looking at the stats, the slowest query for s read seems very bad:

```
  Slowest:	0.2442 secs.
```

Not sure what happened there. We could help to look into this if you can provide more info so that we can reproduce.

**Comment by cw9** [comment]
result with 1 client 1 conn looks much more sane 
```

./main --conns=1 --clients=1 --endpoints=ip2 range "key1" --total=10000 --consistency=l
bench with linearizable range
Summary:
  Total:	7.4256 secs.
  Slowest:	0.0183 secs.
  Fastest:	0.0006 secs.
  Average:	0.0007 secs.
  Stddev:	0.0003 secs.
  Requests/sec:	1346.6996

./main --conns=1 --clients=1 --endpoints=ip1 range "key1" --total=10000 --consistency=s
bench with serializable range
Summary:
  Total:	2.6003 secs.
  Slowest:	0.0017 secs.
  Fastest:	0.0002 secs.
  Average:	0.0003 secs.
  Stddev:	0.0000 secs.
  Requests/sec:	3845.6569
```
I'm getting similar results when running the commands with all 3 hosts in the --endpoints argument as well.


I'm running on HDD machines with 48G memory. I was expecting slower results than the one you posted due to slower disk, but for puts I'm getting slightly better throughput
```

./main --conns=100 --clients=1000 --endpoints=ip1,ip2,ip3 put --key-size=8 --sequential-keys --total=100000 --val-size=256 --key-space-size=100000
Summary:
  Total:	2.5904 secs.
  Slowest:	0.1554 secs.
  Fastest:	0.0012 secs.
  Average:	0.0256 secs.
  Stddev:	0.0120 secs.
  Requests/sec:	38604.3884
```
