### ISSUE TITLE
quay.io/coreos/etcd HTTPS Health Check

### ISSUE THREAD

**Issue by AverageHumanoid** [coreos/etcd#7969]
I want to run the official etcd image in Docker Compose with TLS. Other services in the compose file depend on etcd so I have a health check dependency setup such as with
```
  proxy:
    image: quay.io/coreos/etcd:latest
    ...
    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO- http://127.0.0.1:2379/health || exit 1

  skydns:
    image: gcr.io/google_containers/skydns:2015-10-13-8c72f8c
    ...
    depends_on:
      proxy:
        condition: service_healthy
```
That worked fine using HTTP but as I'm transitioning to HTTPS, the following
```
  proxy:
    image: quay.io/coreos/etcd:latest
    ...
    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO- https://127.0.0.1:2379/health || exit 1
```
no longer work unless I install the `libressl` package in Alpine Linux that 
forces me to maintain my own image which is not ideal.
