### ISSUE TITLE
etcd tls cert requirements clarification

### ISSUE THREAD

**Issue by ElijahCaine** [coreos/etcd#8328]
# Clarification Request

I'm trying to run a single-node etcd cluster with custom TLS certificates generated by Terraform (code below). When I get the node deployed I get the following error on my local client trying to connect to that node: 
```
failed to check the health of member da6937d2522edbd8 on https://$PUBLIC_IP:2379: Get https://$PUBLIC_IP:2379/health: x509: cannot validate certificate for $PUBLIC_IP because it doesn't contain any IP SANs
member da6937d2522edbd8 is unreachable: [https://$PUBLIC_IP:2379] are all unreachable
cluster is unhealthy
```

The logs listed in `systemctl status etcd-member` on the node is as follows:
```
Jul 28 13:51:21 pipewrench etcd-wrapper[1002]: 2017-07-28 13:51:21.231871 I | raft: da6937d2522edbd8 received MsgVoteResp from da6937d2522edbd8 at term 2
Jul 28 13:51:21 pipewrench etcd-wrapper[1002]: 2017-07-28 13:51:21.232730 I | raft: da6937d2522edbd8 became leader at term 2
Jul 28 13:51:21 pipewrench etcd-wrapper[1002]: 2017-07-28 13:51:21.233489 I | raft: raft.node: da6937d2522edbd8 elected leader da6937d2522edbd8 at term 2
Jul 28 13:51:21 pipewrench etcd-wrapper[1002]: 2017-07-28 13:51:21.235621 I | etcdserver: setting up the initial cluster version to 3.2
Jul 28 13:51:21 pipewrench systemd[1]: Started etcd (System Application Container).
Jul 28 13:51:21 pipewrench etcd-wrapper[1002]: 2017-07-28 13:51:21.242432 N | etcdserver/membership: set the initial cluster version to 3.2
Jul 28 13:51:21 pipewrench etcd-wrapper[1002]: 2017-07-28 13:51:21.243430 I | etcdserver/api: enabled capabilities for version 3.2
Jul 28 13:51:21 pipewrench etcd-wrapper[1002]: 2017-07-28 13:51:21.243590 I | etcdserver: published {Name:pipewrench ClientURLs:[https://$PUBLIC_IP:2379]} to cluster f8d9e9a1dffddfbd
Jul 28 13:51:21 pipewrench etcd-wrapper[1002]: 2017-07-28 13:51:21.243623 I | embed: ready to serve client requests
Jul 28 13:51:21 pipewrench etcd-wrapper[1002]: 2017-07-28 13:51:21.244679 I | embed: serving client requests on $PUBLIC_IP:2379
```
The service is active and running.

The Terraform file and Container Linux Config are listed below.

Container Linux Config:
```yaml
etcd:
  version:                     "3.2.4"
  name:                        "{HOSTNAME}"
  advertise_client_urls:       "https://{PUBLIC_IPV4}:2379"
  listen_client_urls:          "https://{PUBLIC_IPV4}:2379"
  initial_advertise_peer_urls: "https://{PRIVATE_IPV4}:2380"
  listen_peer_urls:            "https://{PRIVATE_IPV4}:2380"
  initial_cluster:             "{HOSTNAME}=https://{PRIVATE_IPV4}:2380"
  trusted_ca_file:             "${ca_pem_path}"
  cert_file:                   "${etcd_pem_path}"
  key_file:                    "${etcd_key_path}"
  peer_cert_file:              "${etcd_pem_path}"
  peer_key_file:               "${etcd_key_path}"
  peer_client_cert_auth:       true
  client_cert_auth:            true
update:
  group:  "alpha"
storage:
  files:
  - filesystem: root
    path: ${ca_pem_path}
    contents:
      inline: ${ca_pem}
    mode: 0644
    user:
      id: 232
    group:
      id: 0
  - filesystem: root
    path: ${etcd_pem_path}
    contents:
      inline: ${etcd_pem}
    mode: 0644
    user:
      id: 232
    group:
      id: 0
  - filesystem: root
    path: ${etcd_key_path}
    contents:
      inline: ${etcd_key}
    mode: 0600
    user:
      id: 232
    group:
      id: 0
```

Terraform file:
```text
resource "tls_private_key" "root" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P521"
}

resource "tls_self_signed_cert" "root" {
  key_algorithm   = "ECDSA"
  private_key_pem = "${tls_private_key.root.private_key_pem}"

  validity_period_hours = 26280
  early_renewal_hours   = 8760

  is_ca_certificate = true

  allowed_uses = ["cert_signing", "key_encipherment", "server_auth", "client_auth"]

  subject {
    common_name = "Autogenerated Cert"
  }
}

resource "tls_private_key" "etcd" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P521"
}

resource "tls_cert_request" "etcd" {
  key_algorithm   = "${tls_private_key.etcd.algorithm}"
  private_key_pem = "${tls_private_key.etcd.private_key_pem}"

  subject {
    common_name = "${var.etcd_dns}"
  }

  dns_names = ["${var.etcd_dns}", "localhost"]
}

resource "tls_locally_signed_cert" "etcd" {
  cert_request_pem = "${tls_cert_request.etcd.cert_request_pem}"

  ca_key_algorithm   = "${tls_private_key.root.algorithm}"
  ca_private_key_pem = "${tls_private_key.root.private_key_pem}"
  ca_cert_pem        = "${tls_self_signed_cert.root.cert_pem}"
validity_period_hours = 17520
  early_renewal_hours   = 8760

  allowed_uses = ["server_auth", "client_auth"]
}

data "template_file" "config" {
  template = "${file("config.tpl")}"

  vars {
    ca_pem_path   = "/var/lib/etcd/certs/ca.pem"
    ca_pem        = "${jsonencode(tls_self_signed_cert.root.cert_pem)}"
    
    etcd_key_path = "/var/lib/etcd/certs/etcd.key"
    etcd_key      = "${jsonencode(tls_private_key.etcd.private_key_pem)}"

    etcd_pem_path = "/var/lib/etcd/certs/etcd.pem"
    etcd_pem      = "${jsonencode(tls_locally_signed_cert.etcd.cert_pem)}"
  }
}

resource "local_file" "ca" {
  content  = "${tls_self_signed_cert.root.cert_pem}"
  filename = "ca.pem"
}

resource "local_file" "key" {
  content  = "${tls_locally_signed_cert.etcd.cert_pem}"
  filename = "etcd.pem"
}

resource "local_file" "pem" {
  content  = "${tls_private_key.etcd.private_key_pem}"
  filename = "etcd.key"
}

resource "null_resource" "ct_render" {
  depends_on = ["local_file.config"]
  provisioner "local-exec" {
    command = "ct --platform=digitalocean < config.yaml > config.json"
  }
}

provider "digitalocean" {
  token = "${var.do_token}"
}

resource "digitalocean_droplet" "etcd" {
  depends_on = ["null_resource.ct_render"]

  ssh_keys           = ["${var.do_ssh_key}"]
  image              = "${var.do_image}"
  region             = "${var.do_region}"
  size               = "${var.do_size}"
  private_networking = "${var.do_networking_private}"
  name               = "${var.do_name}"
  user_data          = "${file("config.json")}"
}

resource "digitalocean_domain" "etcd"  {
  name       = "${var.etcd_dns}"
  ip_address = "${digitalocean_droplet.etcd.ipv4_address}"
}

resource "digitalocean_record" "etcd_dns" {
  domain = "${var.my_domain}"
  type   = "A".
  name   = "${var.etcd_name}"
  value  = "${digitalocean_droplet.etcd.ipv4_address}"
  ttl    = "60"
}
```

The above configs successfully create a CoreOS alpha node on Digital Ocean with the generated certs placed in `/var/lib/etcd/certs/` on the host, but when connecting to the node it complains about no IP SANs. Is this expected behavior?

If this is expected behavior, what is the suggested method of spinning up secure etcd nodes using Container Linux Configs? These configs tend to be used on cloud providers where you don't know your IP addresses until you've created and finished provisioning the node it seems *impossible* to meet a "include your IP address in the certificate" requirement. I'm probably missing a conceptual hurdle, but if I am then I bet other people are as well.

A clarification of the expected behavior and some guidance would be much appreciated. I'd be more than happy to make edits to https://github.com/coreos/etcd/blob/master/Documentation/op-guide/security.md#with-peer-certificate-authentication-i-receive-certificate-is-valid-for-127001-not-my_ip once I get my own confusion cleared up.

----

*Edit*: When I created the cert with an *incorrect* dns name I got the following output from etcdctl:
```
error #0: x509: certificate is valid for $CORRECT_DNS_NAME, not $TYPO_DNS_NAME
```
Which lead me to believe that all I needed was a DNS entry not an IP address.
