### ISSUE TITLE
vendoring clientv3 with glide vendors packages twice

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#8441]
Given:
```yaml
package: main
import:
- package: github.com/coreos/etcd
  subpackages:
  - clientv3
```
glide double vendors packages into github.com/coreos/etcd/cmd/vendor. This contributes to 56kloc out of 140kloc of dependencies.
