### ISSUE TITLE
The ETCD_LISTEN_CLIENT_URLS does not work in etcd docker-compose

### ISSUE THREAD

**Issue by ovdevops** [coreos/etcd#9406]
Hi All,
My docker-compose.yml has coredns and etcd.

`
docker-compose.yml
coredns:
    image: coredns/coredns
    command: -conf /data/Corefile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - "./Corefile:/data/Corefile"
    links:
      - etcd1
etcd1:
    image: quay.io/coreos/etcd:v3.2.5
    restart: always
    ports:
        - 0.0.0.0:2379:2379
        - 0.0.0.0:2380:2380
    environment:
        - "ETCD_NAME: node0"
        - "ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380"
        - "ETCD_INITIAL_CLUSTER: node0=http://etcd1:2380"
        - "ETCD_INITIAL_CLUSTER_STATE: new"
        - "ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster"
        - "ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379"
        - "ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380"
        - "ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379"
        - "ETCD_DATA_DIR: /data"
    volumes:
        - "./etcd-data:/default.etcd"

Corefile
.:53 {
     proxy . 8.8.8.8:53
     etcd example.com {
       stubzones
       fallthrough
       path /
       endpoint http://etcd1:2379
       upstream /etc/resolv.conf 
     }
     debug
     errors stdout
     log
}
`
I already list the "ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379" but etcd1 container does not recognize it. When I start the docker-compose, the etcdctl only listen to the 127.0.0.1:2379 as log below.

**Log**:
....
etcd1_1    | 2018-03-08 04:12:42.550271 I | embed: listening for peers on http://localhost:2380
etcd1_1    | 2018-03-08 04:12:42.550443 I | embed: **listening for client requests on localhost:2379**
etcd1_1    | 2018-03-08 04:12:42.552595 I | etcdserver: name = default
.....
etcd1_1    | 2018-03-08 04:12:42.954070 I | etcdserver: published {Name:default ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32
etcd1_1    | 2018-03-08 04:12:42.954262 I | embed: ready to serve client requests
etcd1_1    | 2018-03-08 04:12:42.954541 N | embed: serving insecure client requests on **127.0.0.1:2379**, this is strongly discouraged!

The "dig @localhost example.com" does not return the ip address as I wanted.

However, when I add the command as below for the etcd1 container, it works.
`
....
volumes:
        - "./etcd-data:/default.etcd"
command: sh -c 'etcd -listen-client-urls http://0.0.0.0:2379 -advertise-client-urls http://etcd1:2379'
`

I can now see IP address when executing "dig @localhost example.com".

Is it a bug or work as design ?

Thanks

**Comment by yudai** [comment]
I think

```
- "ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380"
```

should be 

```
- "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
```

(https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers)

**Comment by hexfusion** [comment]
@ovdevops here is a snippet from a working config. Please note indentation etc.
```
docker-compose.yml                                                                                                                                                                                                     ◀◀ [buffers]
version: '2'
services:

    etcd1:
        image: quay.io/coreos/etcd:v3.2.5
        restart: always
        ports:
            - 2379
            - 2280
        volumes:
          - ./etcd-data:/data
        environment:
            ETCD_NAME: node0
            ETCDCTL_API: 3
            ETCD_DEBUG: 1
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2280
            ETCD_INITIAL_CLUSTER: node0=http://etcd1:2280
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluser
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2280
            ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379
            ETCD_DATA_DIR: /data
```
